// <auto-generated />
using System;
using LeagueScheduler.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeagueScheduler.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeagueScheduler.Features.Courts.Entities.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessNotes")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("HoursOfOperation")
                        .HasColumnType("text");

                    b.Property<bool>("Lighted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NumberOfCourts")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("StateProvince")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Leagues.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("RequireApprovalToJoin")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Leagues.Entities.LeaguePlayer", b =>
                {
                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.HasKey("LeagueId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("LeaguePlayers");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Players.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nudge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PreferencePercent")
                        .HasColumnType("double precision");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnavailableDates")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Scheduling.Entities.ScheduleMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CourtId")
                        .HasColumnType("uuid");

                    b.Property<int>("CourtNumber")
                        .HasColumnType("integer")
                        .HasColumnName("Court");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlayerIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ScheduleResultId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("ScheduleResultId");

                    b.ToTable("ScheduleMatches");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Scheduling.Entities.ScheduleResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedCounts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Conflicts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("FairnessToleranceUsed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetCounts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("ScheduleResults");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Seasons.Entities.PrePlannedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CourtId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("boolean");

                    b.Property<string>("PlayerIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("SeasonId");

                    b.ToTable("PrePlannedEvents");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Seasons.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DaysOfWeek")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NonPlayDates")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Seasons.Entities.SeasonCourt", b =>
                {
                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("SeasonId", "CourtId");

                    b.HasIndex("CourtId");

                    b.ToTable("SeasonCourts");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Leagues.Entities.LeaguePlayer", b =>
                {
                    b.HasOne("LeagueScheduler.Features.Leagues.Entities.League", "League")
                        .WithMany("LeaguePlayers")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeagueScheduler.Features.Players.Entities.Player", "Player")
                        .WithMany("LeaguePlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Scheduling.Entities.ScheduleMatch", b =>
                {
                    b.HasOne("LeagueScheduler.Features.Courts.Entities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId");

                    b.HasOne("LeagueScheduler.Features.Scheduling.Entities.ScheduleResult", "ScheduleResult")
                        .WithMany("Matches")
                        .HasForeignKey("ScheduleResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("ScheduleResult");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Scheduling.Entities.ScheduleResult", b =>
                {
                    b.HasOne("LeagueScheduler.Features.Seasons.Entities.Season", "Season")
                        .WithMany("ScheduleResults")
                        .HasForeignKey("SeasonId");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Seasons.Entities.PrePlannedEvent", b =>
                {
                    b.HasOne("LeagueScheduler.Features.Courts.Entities.Court", "Court")
                        .WithMany()
                        .HasForeignKey("CourtId");

                    b.HasOne("LeagueScheduler.Features.Seasons.Entities.Season", "Season")
                        .WithMany("PrePlannedEvents")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Seasons.Entities.Season", b =>
                {
                    b.HasOne("LeagueScheduler.Features.Leagues.Entities.League", "League")
                        .WithMany("Seasons")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Seasons.Entities.SeasonCourt", b =>
                {
                    b.HasOne("LeagueScheduler.Features.Courts.Entities.Court", "Court")
                        .WithMany("SeasonCourts")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeagueScheduler.Features.Seasons.Entities.Season", "Season")
                        .WithMany("SeasonCourts")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Courts.Entities.Court", b =>
                {
                    b.Navigation("SeasonCourts");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Leagues.Entities.League", b =>
                {
                    b.Navigation("LeaguePlayers");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Players.Entities.Player", b =>
                {
                    b.Navigation("LeaguePlayers");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Scheduling.Entities.ScheduleResult", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("LeagueScheduler.Features.Seasons.Entities.Season", b =>
                {
                    b.Navigation("PrePlannedEvents");

                    b.Navigation("ScheduleResults");

                    b.Navigation("SeasonCourts");
                });
#pragma warning restore 612, 618
        }
    }
}
